foo = 10

print(foo)

# error occur
print(bar)
